### ISSUE TITLE
Target SDK version robolectric fix

### ISSUE THREAD

**Issue by qmar** [grandstaish/hello-mvp-dagger-2#2]
Hey there!

I've noticed this line in config:

     targetSdkVersion 21 // Robolectric...

There is an easy fix (at least it worked for me) to set the targetSdkVersion to 23. Simply add the sdk=*target_sdk* to the @Config annotation in tests. Like so:

    @Config(constants = BuildConfig.class,
        application = TestApp.class, sdk = 16)

Thanks for this example project!

**Comment by grandstaish** [comment]
Thanks for this. Applied the fix in 406a6b0
