### ISSUE TITLE
Error: HelloModel cannot be provided without an @Inject constructor or from an @Provides- or @Produces-annotated method.

### ISSUE THREAD

**Issue by FHellmann** [grandstaish/hello-mvp-dagger-2#3]
I have build my project up with the help of your great sample project. But now I'm getting the compile error 'Error: HelloModel cannot be provided without an @Inject constructor or from an @Provides- or @Produces-annotated method.' all the time.
I think, that there is a scoping issue. My Presenter class can not inject the HelloModel due to this compile error. But I already defined everything else like you did.

Have you had the same issue? How do you solved this issue?

**Comment by grandstaish** [comment]
It's really hard to say without seeing code. I assume your presenter class have the @Inject constructor (even if it's empty) like the one in the sample? (https://github.com/grandstaish/hello-mvp-dagger-2/blob/master/app/src/main/java/com/example/bradcampbell/presentation/HelloPresenter.java)

**Comment by FHellmann** [comment]
I've solved the issue.

The problem was, that I haven't had the get methods inside of the component interface so the class could not be found by the injection.

**Comment by grandstaish** [comment]
Ah yes. Yeah Dagger 2 is quite a bit more manual work than Dagger 1. Glad your problem is solved.
