### ISSUE TITLE
Duplicate Presenters Created

### ISSUE THREAD

**Issue by ryanjohn1** [grandstaish/hello-mvp-dagger-2#4]
I'm using this project as a guide to using Compartment with Dagger 2.
I've found that everything works great if I don't access the presenter from the fragment but as soon as I call getPresenter or inject a presenter into the fragment so that I can call through to the presenter from the fragment (such as in an OnClick method) I find I have a second presenter. This new presenter hasn't had bindView called on it so my method calls fail.

I'd assumed that the HelloScope you have defined in your component would cause the reuse of the same presenter when in that scope but I'm quite new to Dagger so I may be completely misunderstanding the scoping system.

Is there a different way I should be accessing the presenter from the fragment or is there a way to modify the component to make sure I only have one presenter for each instance of that fragment.

I think this is a great project and library by the way, hoping to understand it better.

**Comment by grandstaish** [comment]
Hmm, is your presenter annotated with your scope too? e.g. https://github.com/grandstaish/hello-mvp-dagger-2/blob/master/app/src/main/java/com/example/bradcampbell/presentation/HelloPresenter.java

**Comment by ryanjohn1** [comment]
You are completely right, I forgot to add that. I was sure I'd copied the exact structure you had. I guess in my head I thought that applying the scope to the component would be enough as it creates the presenter, but really on the object itself makes sense as that is what you do with the singleton annotation.

Thanks a lot for taking the time, I really like both the library and this example project.

**Comment by grandstaish** [comment]
No problem, I'm glad it helped
